### PR TITLE
property name containing number

### PR DESCRIPTION
**Pull request by halllo**
My ViewModel has properties that contain numbers in their names. Binding those does not work and I added a test case.

I tracked it down to the '!Regex.IsMatch(match, @"\d")' condition in Binding.GetSourcePropertiesPathes. How can I get it to bind to those properties as well?

### CODE REVIEW

**Comment by Alex141** [comment]
Hi, halllo!

Thank you for finding this bug, excellent! I think resolving way is to modify  '!Regex.IsMatch(match, @"\d")' to say, Double.TryParse(match, out result). Have you any different ideas?

**Comment by halllo** [comment]
Ok, I substituted the regex.ismatch with the double.tryparse. Cannot think of a better solution. All the tests are passing again.

**Comment by Alex141** [comment]
Ok, thank you very much! I will accept your changes and build new version today-tomorrow!

Отправлено из  мобильной Почты Mail.Ru

Среда, 21 октября 2015 г., 13:44 +0400 от Manuel Naujoks  <notifications@github.com>:
Ok, I substituted the regex.ismatch with the double.tryparse. Cannot think of a better solution. All the tests are passing again.

**Comment by Alex141** [comment]
halllo, ok, version 2.2.5 contains these changes, good luck!!

**Pull request merged**
